- src/constants.ts
- src/index.ts
I added the consumer-api-routes as described in the consumer-api-concept
There is no functionality added or changed in this PR, and the routes are not in use yet. You can see if the routes look correct to you, but you can't really test them yet.
> ✨ Add consumer-api-routes

- package.json
- src/iconsumer_api_controller.ts
- src/iconsumer_api_router.ts
- src/index.ts
~~⏰ Waits on #1~~
I added interfaces for the consumer_api_router and consumer_api_controller
As this is not functionality, but interfaces, you can only check if they seem correct to you
> ✨ add router and controller interfaces

- package.json
> WIP: Feature/update major for data model dependencies

- package.json
- src/data_models/event/event.ts
- src/data_models/user_task/user_task.ts
Closes #19 
Related to
* https://github.com/process-engine/consumer_api_core/pull/30
* https://github.com/process-engine/process_engine/pull/98
* https://github.com/process-engine/process_engine_contracts/pull/34
The changes to the `Event` were made to be able to finish this rather big PRs:
* https://github.com/process-engine/consumer_api_core/pull/30
* https://github.com/process-engine/process_engine/pull/98
It seems that the `Event` use cases are not thoroughly implemented yet. Therefore there might be bigger changes to the concept as a whole in a future PR.
See https://github.com/process-engine/process_engine/pull/98.
> Use new object model

- package.json
- src/data_models/process_model/process_start_response_payload.ts
Closes https://github.com/process-engine/consumer_api_contracts/issues/25
This PR adds the properties requested in the Issue above to the `ProcessStartResponsePayload`.
See https://github.com/process-engine/process_engine_meta/pull/99.
> extend process start response

- gulpfile.js
- package.json
- src/consumer_context.ts
- src/consumer_request.ts
- src/correlation_result.ts
- src/data_models/event/event.ts
- src/data_models/event/event_list.ts
- src/data_models/event/event_trigger_payload.ts
- src/data_models/index.ts
- src/data_models/pagination_info.ts
- src/data_models/process_model/process_model.ts
- src/data_models/process_model/process_model_list.ts
- src/data_models/process_model/process_start_request_payload.ts
- src/data_models/process_model/process_start_response_payload.ts
- src/data_models/process_model/start_callback_type.ts
- src/data_models/user_task/user_task.ts
- src/data_models/user_task/user_task_config.ts
- src/data_models/user_task/user_task_enum_value.ts
- src/data_models/user_task/user_task_form_field.ts
- src/data_models/user_task/user_task_form_field_type.ts
- src/data_models/user_task/user_task_list.ts
- src/data_models/user_task/user_task_result.ts
- src/iconsumer_api_accessor.ts
- src/iconsumer_api_service.ts
- src/rest_settings.ts
- Adds code documentation to the consumer api components.
- Remove unused pagination_info class.
> Document consumer api components

- gulpfile.js
> Add AMD module system

- src/data_models/user_task/user_task_config.ts
- src/data_models/user_task/user_task_form_field.ts
* added optional `preferedControl` property to `UserTaskConfig`
* https://github.com/process-engine/process_engine_meta/pull/120
* https://github.com/process-engine/consumer_api_meta/pull/38
> Add prefered control to user task config

- package.json
- src/iconsumer_api_accessor.ts
- src/iconsumer_api_service.ts
**Changes:**
- Make `userTaskResult` optional, when finishing user tasks
- Refactor the IConsumerApiService documentation to make it look nicer
Issues: https://github.com/process-engine/process_engine_runtime/issues/18
PR: #33
Try to finish a user task without providing form field results.
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- Fixes Wrong Text Decoration …
> ♻️ Make user task result optional

- dotnet/src/ProcessEngine.ConsumerAPI.Contracts.csproj
**Changes:**
1. Bumped package version of .NET nuget package to 7.0.0
**Issues:**
PR: #39 
---
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- ...
**Issues:**
Closes …
> :arrow_up: Bumped package version of .NET nuget package to 7.0.0

- typescript/package.json
- typescript/src/data_models/index.ts
- typescript/src/data_models/messages/bpmn_events/base_bpmn_event_message.ts
- typescript/src/data_models/messages/bpmn_events/end_event_reached.ts
- typescript/src/data_models/messages/bpmn_events/index.ts
- typescript/src/data_models/messages/bpmn_events/message_event_reached.ts
- typescript/src/data_models/messages/bpmn_events/signal_event_reached.ts
- typescript/src/data_models/messages/bpmn_events/terminate_end_event_reached.ts
- typescript/src/data_models/messages/callback_types.ts
- typescript/src/data_models/messages/event_aggregator_settings.ts
- typescript/src/data_models/messages/index.ts
- typescript/src/data_models/messages/system_events/base_system_event_message.ts
- typescript/src/data_models/messages/system_events/finish_user_task.ts
- typescript/src/data_models/messages/system_events/index.ts
- typescript/src/data_models/messages/system_events/process_ended.ts
- typescript/src/data_models/messages/system_events/process_terminated.ts
- typescript/src/data_models/messages/system_events/user_task_finished.ts
- typescript/src/data_models/messages/system_events/user_task_reached.ts
- typescript/src/iconsumer_api.ts
- typescript/src/index.ts
- typescript/src/socket_settings.ts
**Changes:**
1. Removed usage of obsolete npm scripts `build-schemas` and `build-doc`.
2. Added `onUserTaskWaiting` to `IConsumerApiService` to subscribe to `UserTaskWaitingMessage`.
3. Added `onUserTaskFinished` to `IConsumerApiService` to subscribe to `UserTaskFinishedMessage`.
4. Added `onProcessEnded` to `IConsumerApiService` to subscribe to `ProcessEndedMessage`.
5. Added `onProcessTerminated` to `IConsumerApiService` to subscribe to `ProcessEndedMessage`.
6. Added parameter `processEndedCallback ` to method `startProcessInstance` of `IConsumerApiService` as a shortcut to subscribe to the corresponding `ProcessEndedMessage`.
7. Added `socketSettings` to have a singular point for route and namespace declarations used in the `ConsumerApiSocketEndpoint`.
**Issues:** …
> ✨ Add async notifications

- Jenkinsfile-dotnet
- dotnet/src/ProcessEngine.ConsumerAPI.Contracts.csproj
**Changes:**
1. Add publish step in Jenkinsfile-dotnet
**Issues:**
PR: #42
---
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- ...
**Issues:** …
> :construction_worker: Auto Publish NuGet Packages On Master

- typescript/package.json
- typescript/src/data_models/messages/event_aggregator_settings.ts
- typescript/src/data_models/user_task/user_task.ts
- typescript/src/iconsumer_api.ts
- typescript/src/rest_settings.ts
**Changes:**
1. Add the `FlowNodeInstanceId` to the UserTask datatype.
2. Use Instance IDs for UserTask Http Requests, instead of ModelIds.
3. Use Instance IDs for UserTask Events, instead of ModelIds.
4. Change the parameter names for the `finishUserTask` UseCase to indicate InstanceIds, not ModelIds.
**Issues:**
Part of https://github.com/process-engine/process_engine_runtime/issues/126
PR: #75
Implement the Contracts and use the defined routes and events to handle UserTasks.
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
:twisted_rightwards_arrows: :bug: …
> ♻️🔒 Use unique ids for UserTask events

- typescript/src/data_models/event/event.ts
- typescript/src/data_models/event/event_trigger_payload.ts
- typescript/src/data_models/event/event_type.ts
- typescript/src/data_models/event/index.ts
- typescript/src/iconsumer_api.ts
- typescript/src/rest_settings.ts
**Changes:**
1. Updates necessary types to implement Event API.
**Issues:**
Relates to: https://github.com/process-engine/consumer_api_core/pull/73
PR: #46
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- ... …
> ✨Implement Event API

- typescript/src/iconsumer_api.ts
**Changes:**
1. Add identity to events
**Issues:**
Related to https://github.com/process-engine/process_engine_runtime/issues/142
PR: #47
- **Have a look at https://github.com/process-engine/process_engine_runtime/pull/151**
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- ...
**Issues:**
Closes …
> 🔒 Add Identity to Events

- typescript/package.json
- typescript/src/data_models/messages/callback_types.ts
- typescript/src/data_models/messages/event_aggregator_settings.ts
- typescript/src/data_models/messages/system_events/index.ts
- typescript/src/data_models/messages/system_events/process_started.ts
- typescript/src/iconsumer_api.ts
- typescript/src/rest_settings.ts
- typescript/src/socket_settings.ts
---
**Changes:**
1. Add a message which is send, when a ProcessInstance started
**Issues:**
Related: https://github.com/process-engine/process_engine_runtime/issues/134
PR: #48
---
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- …
> ✨ Implement ProcessStarted Notification

- typescript/src/data_models/messages/internal/index.ts
- typescript/src/data_models/messages/public/index.ts
- typescript/src/data_models/process_model/process_start_response_payload.ts
> Related to https://github.com/process-engine/process_engine_runtime/pull/194
**Changes:**
1. Add ProcessInstanceId to ProcessStartResponsePayload
2. Fix Imports
PR: #49 
-  **Have a look at https://github.com/process-engine/bpmn-studio/pull/1225**
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- ... …
> ✨ Add ProcessInstanceId to Start Result

- typescript/src/data_models/user_task/user_task_config.ts
**Changes:**
1. :sparkles: add description and finishedMessage for UserTasks
PR: #51 
---
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- ...
**Issues:**
Closes …
> :sparkles: add description and finishedMessage for UserTasks

- .editorconfig
- dotnet/src/IConsumerAPI.cs
- dotnet/src/ProcessEngine.ConsumerAPI.Contracts.csproj
- dotnet/src/RestSettings.cs
- dotnet/src/data_models/CorrelationResult.cs
- dotnet/src/data_models/ProcessInstance.cs
- dotnet/src/data_models/process_model/ProcessStartRequestPayload.cs
- dotnet/src/data_models/process_model/ProcessStartResponsePayload.cs
- dotnet/src/data_models/process_model/StartCallbackType.cs
**Changes:**
1. Added namespace `RestSettings` to .NET implementation
2. Added `.editorconfig`
PR: #56 
---
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- ...
**Issues:**
PR: #NumberOfThisPR
</code>
</pre>
</details>
<details>
<summary>
Expand for a list of most used Emojis. …
> ✨ Add rest settings for .NET

- dotnet/src/ProcessEngine.ConsumerAPI.Contracts.csproj
- dotnet/src/data_models/process_model/ProcessStartRequestPayload.cs
---
**Changes:**
1. Added formerly commented out property
PR: #57 
---
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- ...
**Issues:**
PR: #NumberOfThisPR
</code>
</pre>
</details>
<details>
<summary>
Expand for a list of most used Emojis.
</summary>
<br>
Please prefix your commit …
> 🐛 Fix missing property

- typescript/src/apis/imanual_task_consumer_api.ts
- typescript/src/apis/iprocess_model_consumer_api.ts
- typescript/src/apis/iuser_task_consumer_api.ts
- typescript/src/iconsumer_api_http_controller.ts
- typescript/src/rest_settings.ts
> Related to https://github.com/process-engine/process_engine_runtime/pull/207
**Changes:**
1. Add getProcessModelByProcessInstanceId
PR: #53
-  **Have a look at https://github.com/process-engine/bpmn-studio/pull/1225**
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- ...
**Issues:** …
> ✨ Add getProcessModelByProcessInstanceId

- Jenkinsfile-dotnet
**Changes:**
1. Publish all branches to MyGet.
**Issues:**
PR: #60
---
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- ...
**Issues:**
PR: …
> :construction_worker: Implement Feature Branch Publishing For Dotnet

- .editorconfig
- dotnet/src/IConsumerAPI.cs
- dotnet/src/ProcessEngine.ConsumerAPI.Contracts.csproj
- dotnet/src/RestSettings.cs
- dotnet/src/apis/IProcessModelConsumerApi.cs
- dotnet/src/apis/IUserTaskConsumerApi.cs
- dotnet/src/data_models/CorrelationResult.cs
- dotnet/src/data_models/ProcessInstance.cs
- dotnet/src/data_models/process_model/ProcessStartRequestPayload.cs
- dotnet/src/data_models/process_model/ProcessStartResponsePayload.cs
- dotnet/src/data_models/process_model/StartCallbackType.cs
- dotnet/src/data_models/user_task/UserTask.cs
- dotnet/src/data_models/user_task/UserTaskConfig.cs
- dotnet/src/data_models/user_task/UserTaskEnumValue.cs
- dotnet/src/data_models/user_task/UserTaskFormField.cs
- dotnet/src/data_models/user_task/UserTaskFormFieldType.cs
- dotnet/src/data_models/user_task/UserTaskList.cs
- dotnet/src/data_models/user_task/UserTaskResult.cs
---
**Changes:**
1. Added UserTask API to .NET implementation
PR: #66
---
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- ...
**Issues:**
PR: #NumberOfThisPR
</code>
</pre>
</details>
<details>
<summary>
Expand for a list of most used Emojis.
</summary>
<br>
Please prefix your commit …
> 📦 .NET v9.0.0

- typescript/src/apis/iempty_activity_consumer_api.ts
- typescript/src/apis/ievent_consumer_api.ts
- typescript/src/apis/imanual_task_consumer_api.ts
- typescript/src/apis/iprocess_model_consumer_api.ts
- typescript/src/apis/iuser_task_consumer_api.ts
- typescript/src/data_models/correlation_result.ts
- typescript/src/data_models/event/event.ts
- typescript/src/data_models/event/event_list.ts
- typescript/src/data_models/manual_task/manual_task.ts
- typescript/src/data_models/manual_task/manual_task_list.ts
- typescript/src/data_models/process_model/process_model.ts
- typescript/src/data_models/process_model/process_model_list.ts
- typescript/src/data_models/process_model/process_start_request_payload.ts
- typescript/src/data_models/process_model/process_start_response_payload.ts
- typescript/src/data_models/user_task/user_task.ts
- typescript/src/data_models/user_task/user_task_config.ts
- typescript/src/data_models/user_task/user_task_enum_value.ts
- typescript/src/data_models/user_task/user_task_form_field.ts
- typescript/src/data_models/user_task/user_task_form_field_type.ts
- typescript/src/data_models/user_task/user_task_list.ts
- typescript/src/data_models/user_task/user_task_result.ts
- typescript/src/iconsumer_api_http_controller.ts
- typescript/src/iconsumer_socket_io_accessor.ts
- typescript/src/messages/event_aggregator_settings.ts
- typescript/src/messages/system_events/empty_activity_finished.ts
- typescript/src/messages/system_events/empty_activity_reached.ts
- typescript/src/messages/system_events/user_task_reached.ts
**Changes:**
Change the code documentations of the .TS implementation to make it more comprehensive.
1. Add `@throws` sections to all API functions
2. `@returns` now only describes the values that the function returns, not the Promise that wraps the function. That is already covered by the `@async` tag.
3. Remove some docs that serve no useful purpose, such as `The Id.` or `The list.`.
4. Unify usages of terms such as `ID` or `FormFields`.
PR: #68
> 📖 Rewrite the .ts code docs

- Jenkinsfile-dotnet
- dotnet/src/IConsumerAPI.cs
- dotnet/src/RestSettings.cs
- dotnet/src/apis/IManualTaskConsumerApi.cs
- dotnet/src/data_models/event/EventType.cs
- dotnet/src/data_models/manual_task/ManualTask.cs
- dotnet/src/data_models/manual_task/ManualTaskList.cs
- dotnet/src/data_models/process_model/ProcessStartResponsePayload.cs
- dotnet/src/data_models/user_task/UserTaskFormFieldType.cs
**Changes:**
1. Added interface `IManualTaskConsumerAPI` to `IConsumerAPI`
2. Added data models for manual tasks
3. Updated `RestSettings`
4. Fixed missing property `ProcessInstanceId` in `ProcessStartResponsePayload`
5. Updated code documentation in `ManualTask` (TypeScript)
PR: #67
> ✨ Add .NET ManualTaskConsumer API

- dotnet/src/data_models/CorrelationResult.cs
- dotnet/src/data_models/ProcessInstance.cs
- dotnet/src/data_models/event/Event.cs
- dotnet/src/data_models/manual_task/ManualTask.cs
- dotnet/src/data_models/process_model/ProcessStartRequestPayload.cs
- dotnet/src/data_models/process_model/ProcessStartResponsePayload.cs
- dotnet/src/data_models/process_model/StartCallbackType.cs
- dotnet/src/data_models/user_task/UserTask.cs
- dotnet/src/data_models/user_task/UserTaskConfig.cs
- dotnet/src/data_models/user_task/UserTaskEnumValue.cs
- dotnet/src/data_models/user_task/UserTaskFormField.cs
- dotnet/src/data_models/user_task/UserTaskFormFieldType.cs
- dotnet/src/data_models/user_task/UserTaskList.cs
- dotnet/src/data_models/user_task/UserTaskResult.cs
**Changes:**
1. Add missing `public` access modifier to `UserTaskList.UserTasks`.
2. Refactor .NET code documentation to match its .ts counterpart.
PR: #70
Accessing a UserTask list should now work in .NET.
> 🐛 Fix .NET UserTask API contracts

- .gitignore
- Jenkinsfile
- typescript/package-lock.json
1. Switch from normal install to clean install
2. Remove package-lock from gitignore
3. Add package-lock
Closes #YourIssueNumber
PR: #NumberOfThisPR
> Describe how others can test your changes (not required when fixing typos, linter errors and such)
> Switch from install to clean install

- Jenkinsfile
- typescript/package-lock.json
- typescript/package.json
- typescript/src/apis/iprocess_model_consumer_api.ts
- typescript/src/messages/callback_types.ts
- typescript/src/messages/event_aggregator_settings.ts
- typescript/src/messages/system_events/index.ts
- typescript/src/messages/system_events/process_error.ts
- typescript/src/socket_settings.ts
1. Add API contracts and data models for the `onProcessError` notification
2. Only run `npm ci` on Jenkins builds, if the build runs on the `master` or `develop` branch
- This is required for working with feature branches, or else we would have to rewrite the package-lock after every change we make to a referenced dependency
Part of https://github.com/process-engine/process_engine_runtime/issues/348
PR: #74
> ✨Add onProcessError notification

- dotnet/src/IConsumerAPI.cs
- dotnet/src/ProcessEngine.ConsumerAPI.Contracts.csproj
- dotnet/src/RestSettings.cs
- dotnet/src/apis/IEmptyActivityConsumerApi.cs
- dotnet/src/data_models/empty_activity/EmptyActivity.cs
- dotnet/src/data_models/empty_activity/EmptyActivityList.cs
Add interfaces, types and REST settings for .NET `EmptyActivityAPI`.
PR: #75
> ✨ Implement .NET EmptyActivityApi

- typescript/package.json
- typescript/src/apis/iprocess_model_consumer_api.ts
- typescript/src/data_models/process_model/process_start_request_payload.ts
1. Make Payload Optional for StartProcessInstance
Related to https://github.com/process-engine/process_engine_runtime/issues/371
PR: #79
> ♻️ Make Payload Optional for StartProcessInstance

- dotnet/src/ProcessEngine.ConsumerAPI.Contracts.csproj
- dotnet/src/apis/IEmptyActivityConsumerApi.cs
- dotnet/src/apis/IEventConsumerApi.cs
- dotnet/src/apis/IManualTaskConsumerApi.cs
- dotnet/src/apis/IProcessModelConsumerApi.cs
- dotnet/src/apis/IUserTaskConsumerApi.cs
- typescript/src/apis/iempty_activity_consumer_api.ts
- typescript/src/apis/ievent_consumer_api.ts
- typescript/src/apis/imanual_task_consumer_api.ts
- typescript/src/apis/iprocess_model_consumer_api.ts
- typescript/src/apis/iuser_task_consumer_api.ts
Add `offset` and `limit` to all queries that return a list.
Part of https://github.com/process-engine/process_engine_runtime/issues/379
PR: #80
> ✨ Add limit and offset to list queries

- .github/workflows/publish-dotnet.yml
1. Use the regex to replace `/` and `_` global
PR: #88 
Look at the build
> 🐛 Use regex global
